version: 1.0.{build}
configuration: Release
before_build:
- ps: >-
    (new-object net.webclient).DownloadFile('https://download.microsoft.com/download/A/3/8/A38489F3-9777-41DD-83F8-2CBDFAB2520C/packages/DotNetCore.1.0.0-SDK.Preview2-x64.exe','core.exe')
    core.exe /install /quiet /norestart
    dotnet restore
build:
  verbosity: minimal
test_script:
- cmd: dotnet test
